# Import needed libraries

In [1]:
import pandas as pd

In [2]:
nba = pd.read_csv("../data/pandas/nba.csv")

In [3]:
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# .head() and .tail() methods
these are used to return a specific # of rows of data from either the beginning or end of the dataframe.  Default is 5

In [4]:
nba.head() #first 5 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [5]:
nba.tail() #last 5 rows

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Attributes

In [6]:
nba.index

RangeIndex(start=0, stop=458, step=1)

In [7]:
nba.shape #to see the # of rows and columns

(458, 9)

In [8]:
nba.dtypes #find about the datatypes of the different cols of this df

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [9]:
nba.columns # Returns an arraty of the column headings in this df

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [10]:
nba.axes # returns the cols x rows indexes

[RangeIndex(start=0, stop=458, step=1),
 Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
        'College', 'Salary'],
       dtype='object')]

In [11]:
nba.info #provide a summary of the dataframe

<bound method DataFrame.info of                         Name                    Team  Number Position   Age  \
0              Avery Bradley          Boston Celtics     0.0       PG  25.0
1                Jae Crowder          Boston Celtics    99.0       SF  25.0
2               John Holland          Boston Celtics    30.0       SG  27.0
3                R.J. Hunter          Boston Celtics    28.0       SG  22.0
4              Jonas Jerebko          Boston Celtics     8.0       PF  29.0
5               Amir Johnson          Boston Celtics    90.0       PF  29.0
6              Jordan Mickey          Boston Celtics    55.0       PF  21.0
7               Kelly Olynyk          Boston Celtics    41.0        C  25.0
8               Terry Rozier          Boston Celtics    12.0       PG  22.0
9               Marcus Smart          Boston Celtics    36.0       PG  22.0
10           Jared Sullinger          Boston Celtics     7.0        C  24.0
11             Isaiah Thomas          Boston Celtics     4.0       PG  27.0
12               Evan Turner          Boston Celtics    11.0       SG  27.0
13               James Young          Boston Celtics    13.0       SG  20.0
14              Tyler Zeller          Boston Celtics    44.0        C  26.0
15          Bojan Bogdanovic           Brooklyn Nets    44.0       SG  27.0
16              Markel Brown           Brooklyn Nets    22.0       SG  24.0
17           Wayne Ellington           Brooklyn Nets    21.0       SG  28.0
18   Rondae Hollis-Jefferson           Brooklyn Nets    24.0       SG  21.0
19              Jarrett Jack           Brooklyn Nets     2.0       PG  32.0
20            Sergey Karasev           Brooklyn Nets    10.0       SG  22.0
21           Sean Kilpatrick           Brooklyn Nets     6.0       SG  26.0
22              Shane Larkin           Brooklyn Nets     0.0       PG  23.0
23               Brook Lopez           Brooklyn Nets    11.0        C  28.0
24          Chris McCullough           Brooklyn Nets     1.0       PF  21.0
25               Willie Reed           Brooklyn Nets    33.0       PF  26.0
26           Thomas Robinson           Brooklyn Nets    41.0       PF  25.0
27                Henry Sims           Brooklyn Nets    14.0        C  26.0
28              Donald Sloan           Brooklyn Nets    15.0       PG  28.0
29            Thaddeus Young           Brooklyn Nets    30.0       PF  27.0
..                       ...                     ...     ...      ...   ...
428          Al-Farouq Aminu  Portland Trail Blazers     8.0       SF  25.0
429          Pat Connaughton  Portland Trail Blazers     5.0       SG  23.0
430             Allen Crabbe  Portland Trail Blazers    23.0       SG  24.0
431                 Ed Davis  Portland Trail Blazers    17.0        C  27.0
432         Maurice Harkless  Portland Trail Blazers     4.0       SF  23.0
433         Gerald Henderson  Portland Trail Blazers     9.0       SG  28.0
434              Chris Kaman  Portland Trail Blazers    35.0        C  34.0
435           Meyers Leonard  Portland Trail Blazers    11.0       PF  24.0
436           Damian Lillard  Portland Trail Blazers     0.0       PG  25.0
437            C.J. McCollum  Portland Trail Blazers     3.0       SG  24.0
438             Luis Montero  Portland Trail Blazers    44.0       SG  23.0
439            Mason Plumlee  Portland Trail Blazers    24.0        C  26.0
440            Brian Roberts  Portland Trail Blazers     2.0       PG  30.0
441              Noah Vonleh  Portland Trail Blazers    21.0       PF  20.0
442            Trevor Booker               Utah Jazz    33.0       PF  28.0
443               Trey Burke               Utah Jazz     3.0       PG  23.0
444               Alec Burks               Utah Jazz    10.0       SG  24.0
445               Dante Exum               Utah Jazz    11.0       PG  20.0
446           Derrick Favors               Utah Jazz    15.0       PF  24.0
447              Rudy Gobert               Utah Jazz    27.0        C  23.0
448           Gordon Hayward               Utah Jazz    20.0       SF  26.0
449              Rodney Hood               Utah Jazz     5.0       SG  23.0
450               Joe Ingles               Utah Jazz     2.0       SF  28.0
451            Chris Johnson               Utah Jazz    23.0       SF  26.0
452               Trey Lyles               Utah Jazz    41.0       PF  20.0
453             Shelvin Mack               Utah Jazz     8.0       PG  26.0
454                Raul Neto               Utah Jazz    25.0       PG  24.0
455             Tibor Pleiss               Utah Jazz    21.0        C  26.0
456              Jeff Withey               Utah Jazz    24.0        C  26.0
457                      NaN                     NaN     NaN      NaN   NaN

    Height  Weight            College      Salary
0      6-2   180.0              Texas   7730337.0
1      6-6   235.0          Marquette   6796117.0
2      6-5   205.0  Boston University         NaN
3      6-5   185.0      Georgia State   1148640.0
4     6-10   231.0                NaN   5000000.0
5      6-9   240.0                NaN  12000000.0
6      6-8   235.0                LSU   1170960.0
7      7-0   238.0            Gonzaga   2165160.0
8      6-2   190.0         Louisville   1824360.0
9      6-4   220.0     Oklahoma State   3431040.0
10     6-9   260.0         Ohio State   2569260.0
11     5-9   185.0         Washington   6912869.0
12     6-7   220.0         Ohio State   3425510.0
13     6-6   215.0           Kentucky   1749840.0
14     7-0   253.0     North Carolina   2616975.0
15     6-8   216.0                NaN   3425510.0
16     6-3   190.0     Oklahoma State    845059.0
17     6-4   200.0     North Carolina   1500000.0
18     6-7   220.0            Arizona   1335480.0
19     6-3   200.0       Georgia Tech   6300000.0
20     6-7   208.0                NaN   1599840.0
21     6-4   219.0         Cincinnati    134215.0
22    5-11   175.0         Miami (FL)   1500000.0
23     7-0   275.0           Stanford  19689000.0
24    6-11   200.0           Syracuse   1140240.0
25    6-10   220.0        Saint Louis    947276.0
26    6-10   237.0             Kansas    981348.0
27    6-10   248.0         Georgetown    947276.0
28     6-3   205.0          Texas A&M    947276.0
29     6-8   221.0       Georgia Tech  11235955.0
..     ...     ...                ...         ...
428    6-9   215.0        Wake Forest   8042895.0
429    6-5   206.0         Notre Dame    625093.0
430    6-6   210.0         California    947276.0
431   6-10   240.0     North Carolina   6980802.0
432    6-9   215.0         St. John's   2894059.0
433    6-5   215.0               Duke   6000000.0
434    7-0   265.0   Central Michigan   5016000.0
435    7-1   245.0           Illinois   3075880.0
436    6-3   195.0        Weber State   4236287.0
437    6-4   200.0             Lehigh   2525160.0
438    6-7   185.0     Westchester CC    525093.0
439   6-11   235.0               Duke   1415520.0
440    6-1   173.0             Dayton   2854940.0
441    6-9   240.0            Indiana   2637720.0
442    6-8   228.0            Clemson   4775000.0
443    6-1   191.0           Michigan   2658240.0
444    6-6   214.0           Colorado   9463484.0
445    6-6   190.0                NaN   3777720.0
446   6-10   265.0       Georgia Tech  12000000.0
447    7-1   245.0                NaN   1175880.0
448    6-8   226.0             Butler  15409570.0
449    6-8   206.0               Duke   1348440.0
450    6-8   226.0                NaN   2050000.0
451    6-6   206.0             Dayton    981348.0
452   6-10   234.0           Kentucky   2239800.0
453    6-3   203.0             Butler   2433333.0
454    6-1   179.0                NaN    900000.0
455    7-3   256.0                NaN   2900000.0
456    7-0   231.0             Kansas    947276.0
457    NaN     NaN                NaN         NaN

[458 rows x 9 columns]>

# Descriptive methods

In [12]:
#note that there is a .info() method, too.  This one is a better summary, IMO
nba.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [13]:
nba.get_dtype_counts() # returns datatypes and # of columns of that type

float64    4
object     5
dtype: int64

# Differences between shared methods of series and dataframes

In [14]:
rev = pd.read_csv("../data/pandas/revenue.csv", index_col="Date")
rev.head()

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933
1/4/16       730          904    885
1/5/16       114           71    253

In [15]:
rev_series = pd.read_csv("../data/pandas/revenue.csv",usecols=["New York"], squeeze=True)
rev_series.head()

0    985
1    738
2     14
3    730
4    114
Name: New York, dtype: int64

In [16]:
# look at how .sum() behaves differently for series vs. a dataframe
rev_series.sum()

5475

In [17]:
rev.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [18]:
rev.sum(axis = 1) #sum horizontally instead of vertically

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [19]:
rev.sum(axis = 0) #sum vertically

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [20]:
rev.sum(axis = "columns") #another way of summing horizontally

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

# Selecting Columns from DataFrames

In [21]:
#using object notation.  Watch for spaces and case sensitivity.  Returns a series object.
nba.Team

0              Boston Celtics
1              Boston Celtics
2              Boston Celtics
3              Boston Celtics
4              Boston Celtics
5              Boston Celtics
6              Boston Celtics
7              Boston Celtics
8              Boston Celtics
9              Boston Celtics
10             Boston Celtics
11             Boston Celtics
12             Boston Celtics
13             Boston Celtics
14             Boston Celtics
15              Brooklyn Nets
16              Brooklyn Nets
17              Brooklyn Nets
18              Brooklyn Nets
19              Brooklyn Nets
20              Brooklyn Nets
21              Brooklyn Nets
22              Brooklyn Nets
23              Brooklyn Nets
24              Brooklyn Nets
25              Brooklyn Nets
26              Brooklyn Nets
27              Brooklyn Nets
28              Brooklyn Nets
29              Brooklyn Nets
                ...
428    Portland Trail Blazers
429    Portland Trail Blazers
430    Portland Trail Blazers
431    Portland Trail Blazers
432    Portland Trail Blazers
433    Portland Trail Blazers
434    Portland Trail Blazers
435    Portland Trail Blazers
436    Portland Trail Blazers
437    Portland Trail Blazers
438    Portland Trail Blazers
439    Portland Trail Blazers
440    Portland Trail Blazers
441    Portland Trail Blazers
442                 Utah Jazz
443                 Utah Jazz
444                 Utah Jazz
445                 Utah Jazz
446                 Utah Jazz
447                 Utah Jazz
448                 Utah Jazz
449                 Utah Jazz
450                 Utah Jazz
451                 Utah Jazz
452                 Utah Jazz
453                 Utah Jazz
454                 Utah Jazz
455                 Utah Jazz
456                 Utah Jazz
457                       NaN
Name: Team, Length: 458, dtype: object

In [22]:
nba.Position

0       PG
1       SF
2       SG
3       SG
4       PF
5       PF
6       PF
7        C
8       PG
9       PG
10       C
11      PG
12      SG
13      SG
14       C
15      SG
16      SG
17      SG
18      SG
19      PG
20      SG
21      SG
22      PG
23       C
24      PF
25      PF
26      PF
27       C
28      PG
29      PF
      ...
428     SF
429     SG
430     SG
431      C
432     SF
433     SG
434      C
435     PF
436     PG
437     SG
438     SG
439      C
440     PG
441     PF
442     PF
443     PG
444     SG
445     PG
446     PF
447      C
448     SF
449     SG
450     SF
451     SF
452     PF
453     PG
454     PG
455      C
456      C
457    NaN
Name: Position, Length: 458, dtype: object

In [23]:
#using list notation.  This works for cols with spaces, index labels or col positions.
nba["Position"]

0       PG
1       SF
2       SG
3       SG
4       PF
5       PF
6       PF
7        C
8       PG
9       PG
10       C
11      PG
12      SG
13      SG
14       C
15      SG
16      SG
17      SG
18      SG
19      PG
20      SG
21      SG
22      PG
23       C
24      PF
25      PF
26      PF
27       C
28      PG
29      PF
      ...
428     SF
429     SG
430     SG
431      C
432     SF
433     SG
434      C
435     PF
436     PG
437     SG
438     SG
439      C
440     PG
441     PF
442     PF
443     PG
444     SG
445     PG
446     PF
447      C
448     SF
449     SG
450     SF
451     SF
452     PF
453     PG
454     PG
455      C
456      C
457    NaN
Name: Position, Length: 458, dtype: object

In [24]:
#Jupyter trick to hide output
nba.College
Output = None

In [25]:
#notice that the result is a series
type(nba.Position)

pandas.core.series.Series

## Selecting multiple columns

In [26]:
#to get multiple columns, use a list inside the list
player_info = nba[['Name', 'Team', 'College','Salary']]
player_info.head()

            Name            Team            College     Salary
0  Avery Bradley  Boston Celtics              Texas  7730337.0
1    Jae Crowder  Boston Celtics          Marquette  6796117.0
2   John Holland  Boston Celtics  Boston University        NaN
3    R.J. Hunter  Boston Celtics      Georgia State  1148640.0
4  Jonas Jerebko  Boston Celtics                NaN  5000000.0

In [27]:
#you can create this in any order you want.  e.g.,
nba[['College','Team']].head()

             College            Team
0              Texas  Boston Celtics
1          Marquette  Boston Celtics
2  Boston University  Boston Celtics
3      Georgia State  Boston Celtics
4                NaN  Boston Celtics

In [28]:
#store the list you want to extract
headings = ['Name','Team','Salary']
nba[headings].tail()

             Name       Team     Salary
453  Shelvin Mack  Utah Jazz  2433333.0
454     Raul Neto  Utah Jazz   900000.0
455  Tibor Pleiss  Utah Jazz  2900000.0
456   Jeff Withey  Utah Jazz   947276.0
457           NaN        NaN        NaN

## create a new column

In [29]:
# Use assignment to add a new column.  BE CAREFUL.  You don't want to overwrite your existing data
nba['Sport'] = "basketball" # this is a scalar value. It is assigned to every row
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,basketball
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,basketball
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,basketball
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,basketball
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,basketball

In [30]:
nba['League'] = "NBA"
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,basketball,NBA
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,basketball,NBA
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,basketball,NBA
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,basketball,NBA
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,basketball,NBA

In [31]:
# reset dataframe
nba = pd.read_csv("../data/pandas/nba.csv")

In [32]:
#use the .insert() method to add columns wherever you want
nba.insert(3, "Sport","basketball", True)
nba.head()

,Name,Team,Number,Sport,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,basketball,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,basketball,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,basketball,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,basketball,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,basketball,PF,29.0,6-10,231.0,NaN,5000000.0

In [33]:
nba.insert(7,"League","NBA",True)
nba.tail()

,Name,Team,Number,Sport,Position,Age,Height,League,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,basketball,PG,26.0,6-3,NBA,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,basketball,PG,24.0,6-1,NBA,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,basketball,C,26.0,7-3,NBA,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,basketball,C,26.0,7-0,NBA,231.0,Kansas,947276.0
457,NaN,NaN,NaN,basketball,NaN,NaN,NaN,NBA,NaN,NaN,NaN

# Broadcasting

In [34]:
# reset dataframe
nba = pd.read_csv("../data/pandas/nba.csv")

In [35]:
nba["Age"].add(5) # will add 5 to every value.  This will create a new series.  It will not modify the original df
Output = False

In [36]:
#operate on each value in the series
nba["Age"] +5
nba['Age'].sub(4)
nba['Age'] -5 
# multiplication
nba['Weight'].mul(.4567)
nba['Weight'] * .4567

0       82.2060
1      107.3245
2       93.6235
3       84.4895
4      105.4977
5      109.6080
6      107.3245
7      108.6946
8       86.7730
9      100.4740
10     118.7420
11      84.4895
12     100.4740
13      98.1905
14     115.5451
15      98.6472
16      86.7730
17      91.3400
18     100.4740
19      91.3400
20      94.9936
21     100.0173
22      79.9225
23     125.5925
24      91.3400
25     100.4740
26     108.2379
27     113.2616
28      93.6235
29     100.9307
         ...
428     98.1905
429     94.0802
430     95.9070
431    109.6080
432     98.1905
433     98.1905
434    121.0255
435    111.8915
436     89.0565
437     91.3400
438     84.4895
439    107.3245
440     79.0091
441    109.6080
442    104.1276
443     87.2297
444     97.7338
445     86.7730
446    121.0255
447    111.8915
448    103.2142
449     94.0802
450    103.2142
451     94.0802
452    106.8678
453     92.7101
454     81.7493
455    116.9152
456    105.4977
457         NaN
Name: Weight, Length: 458, dtype: float64

# .value_counts() method
note that this is only available on a series (not in df)

In [37]:
#find out how many players are on each team
nba["Team"].value_counts()

New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Golden State Warriors     15
Sacramento Kings          15
Houston Rockets           15
Los Angeles Clippers      15
Detroit Pistons           15
Atlanta Hawks             15
Indiana Pacers            15
Toronto Raptors           15
Charlotte Hornets         15
Oklahoma City Thunder     15
Boston Celtics            15
Cleveland Cavaliers       15
Brooklyn Nets             15
Dallas Mavericks          15
Utah Jazz                 15
Philadelphia 76ers        15
Los Angeles Lakers        15
San Antonio Spurs         15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Phoenix Suns              15
Chicago Bulls             15
Portland Trail Blazers    15
Minnesota Timberwolves    14
Orlando Magic             14
Name: Team, dtype: int64

In [38]:
#How many in each position?
nba['Position'].value_counts()
#what's the most common weight
nba['Weight'].value_counts()
#most common salary
nba['Salary'].value_counts()

947276.0      31
845059.0      18
525093.0      13
981348.0       6
1100602.0      5
16407500.0     5
5000000.0      5
12000000.0     5
8000000.0      5
4000000.0      5
3000000.0      4
7000000.0      4
2814000.0      4
1000000.0      4
19689000.0     4
200600.0       3
8500000.0      3
2500000.0      3
1015421.0      3
2854940.0      3
13500000.0     3
5543725.0      3
2288205.0      2
1270964.0      2
2900000.0      2
1007026.0      2
111444.0       2
13000000.0     2
1500000.0      2
1842000.0      2
              ..
2239800.0      1
1474440.0      1
19688000.0     1
7900000.0      1
2008748.0      1
13800000.0     1
2841960.0      1
1404600.0      1
1584480.0      1
273038.0       1
9213483.0      1
3272091.0      1
3075880.0      1
2250000.0      1
4626960.0      1
1304520.0      1
12100000.0     1
7500000.0      1
295327.0       1
2836186.0      1
6486486.0      1
5016000.0      1
3333333.0      1
1824360.0      1
8042895.0      1
1242720.0      1
2489530.0      1
5103120.0      1
9463484.0      1
700902.0       1
Name: Salary, Length: 309, dtype: int64

# Dealing with NaN values

In [39]:
nba = pd.read_csv("../data/pandas/nba.csv")
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
# the .dropna() drops rows that have ANY null values at all.  BE CAREFUL in using this.
nba.dropna().tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [41]:
#change the "how" parameter to be more specific about what to remove
nba.dropna(how = "all").tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [42]:
# drop specific columns.  Change the axis to cols
nba.dropna(axis = 1)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
#Get more specific.  Look for NaN in specific cols only
nba.dropna(subset = ['Salary', 'College']) #only drop if there is a null value in the Salary column
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# filling in NaN values with a pre-assigned value

In [44]:
nba.fillna(0) #this replaces every NaN with a '0'

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,0,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,0,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,0,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,0,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,0,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,0,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,0,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,0,0,0.0,0,0.0,0,0.0,0,0.0

In [45]:
#filter to only Salary and then fill it in
nba['Salary'].fillna(0, inplace = True)

In [46]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [47]:
#Fill college NaNs with "no college" string value
nba['College'].fillna('no college', inplace = True)
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,no college,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,no college,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,no college,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,no college,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,no college,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,no college,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,no college,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,no college,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,no college,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,no college,0.0

# .astype() method
used to convert datatypes of a series from one type to another.
requires a series to not have any null values.  Therefore, you must convert those first.

In [67]:
nba = pd.read_csv("../data/pandas/nba.csv")

In [69]:
nba.dropna(how= "all", inplace=True)
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [70]:
#drop null values
nba.dropna( how = "all")
nba['Salary'].fillna(0, inplace = True)
nba['College'].fillna('no college', inplace = True)

In [71]:
#check the datatypes
nba.dtypes

Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object

In [72]:
#another way of checking data types.  Advantage of this method is that you can see how much memory is used.
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null float64
dtypes: float64(4), object(5)
memory usage: 35.7+ KB

In [73]:
nba['Salary'] = nba['Salary'].astype('int')

In [75]:
#convert age and number columns to ints
nba['Age'] = nba['Age'].astype('int')
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
452,Trey Lyles,Utah Jazz,41.0,PF,20,6-10,234.0,Kentucky,2239800
453,Shelvin Mack,Utah Jazz,8.0,PG,26,6-3,203.0,Butler,2433333
454,Raul Neto,Utah Jazz,25.0,PG,24,6-1,179.0,no college,900000
455,Tibor Pleiss,Utah Jazz,21.0,C,26,7-3,256.0,no college,2900000
456,Jeff Withey,Utah Jazz,24.0,C,26,7-0,231.0,Kansas,947276

In [76]:
#check for unique values and map all unique values to one location
nba['Position'].nunique()

5

In [77]:
#turn the unique values from a specific column into a category type
nba['Position'] = nba['Position'].astype('category')

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null category
Age         457 non-null int64
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null int64
dtypes: category(1), float64(2), int64(2), object(4)
memory usage: 32.8+ KB

# Sorting dataframes

In [79]:
nba = pd.read_csv("../data/pandas/nba.csv")

In [83]:
#notice that chaining doesn't quite work here.  It resorts the resulting df each time
nba.sort_values('Team').sort_values('Salary').sort_values('Name')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,NaN,4389607.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
287,Alonzo Gee,New Orleans Pelicans,15.0,SF,29.0,6-6,225.0,Alabama,1320000.0
348,Amar'e Stoudemire,Miami Heat,5.0,PF,33.0,6-10,245.0,NaN,947276.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,NaN,289755.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
362,Andrew Nicholson,Orlando Magic,44.0,PF,26.0,6-9,250.0,St. Bonaventure,2380593.0
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680.0
108,Anthony Brown,Los Angeles Lakers,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730.0
421,Anthony Morrow,Oklahoma City Thunder,2.0,SG,30.0,6-5,210.0,Georgia Tech,3344000.0
195,Anthony Tolliver,Detroit Pistons,43.0,PF,31.0,6-8,240.0,Creighton,3000000.0
...,...,...,...,...,...,...,...,...,...
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
325,Troy Daniels,Charlotte Hornets,30.0,SG,24.0,6-4,205.0,Virginia Commonwealth,947276.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
345,Tyler Johnson,Miami Heat,8.0,SG,24.0,6-4,186.0,Fresno State,845059.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
343,Udonis Haslem,Miami Heat,40.0,PF,36.0,6-8,235.0,Florida,2854940.0
363,Victor Oladipo,Orlando Magic,5.0,SG,24.0,6-4,210.0,Indiana,5192520.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,6-7,215.0,Syracuse,1100602.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
385,Will Barton,Denver Nuggets,5.0,SF,25.0,6-6,175.0,Memphis,3533333.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [88]:
#to sort by multiple columns, use a list.  It works for the ascending parameter, too
nba.sort_values(['Team','Salary','Name'], ascending=[True,False,True], inplace = True)
nba.tail(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
370,Jared Dudley,Washington Wizards,1.0,SF,30.0,6-7,225.0,Boston College,4375000.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
372,Drew Gooden,Washington Wizards,90.0,PF,34.0,6-10,250.0,Kansas,3300000.0
379,Ramon Sessions,Washington Wizards,7.0,PG,30.0,6-3,190.0,Nevada,2170465.0
377,Kelly Oubre Jr.,Washington Wizards,12.0,SF,20.0,6-7,205.0,Kansas,1920240.0
380,Garrett Temple,Washington Wizards,17.0,SG,30.0,6-6,195.0,LSU,1100602.0
371,Jarell Eddie,Washington Wizards,8.0,SG,24.0,6-7,218.0,Virginia Tech,561716.0
374,JJ Hickson,Washington Wizards,21.0,C,27.0,6-9,242.0,North Carolina State,273038.0
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [90]:
#sort_index() method works similarly on a df as it does on a series.  Use this to get the original shape back, since I changed it with the last command
nba.sort_index(inplace = True)
nba.tail(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# .rank() method to generate a new series

In [92]:
#must first get rid of null values
nba.dropna(how="all")
nba['Salary'] = nba['Salary'].fillna(0).astype('int')

In [96]:
#first need to extract the column of interest since this is a series operation
nba['Salary Rank'] = nba['Salary'].rank(ascending = False).astype('int')
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337,97
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117,110
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452

In [97]:
#sort by salary to make sure this is accurate
nba.sort_values(by = 'Salary',ascending=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000,1
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500,2
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000,3
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364,4
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730,5
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695,6
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622,7
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064,8
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000,9
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000,11
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000,11
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000,11
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000,11
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,NaN,19688000,14
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726,15
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659,16
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106,17
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218,18
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501,19
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500,22
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500,22
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500,22
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500,22
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500,22
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000,25
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950,26
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950,26
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438,28
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217,29
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031,30
...,...,...,...,...,...,...,...,...,...,...
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177,429
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888,430
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744,431
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192,432
303,Kevin Martin,San Antonio Spurs,23.0,SG,33.0,6-7,199.0,Western Carolina,200600,434
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600,434
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600,434
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455,436
282,Bryce Dejean-Jones,New Orleans Pelicans,31.0,SG,23.0,6-6,203.0,Iowa State,169883,437
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406,438
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215,439
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444,440
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444,440
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196,442
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397,443
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722,444
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722,444
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888,446
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,0,452
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,0,452
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,0,452
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,0,452
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,0,452
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,0,452
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,0,452
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,0,452
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0,452
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,0,452
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,452